samples: "resources/test_samples.tsv"
result_dir: "results"

host_filtering:
  skip_host_filtering: False
  search_engine: "-xtandem"
  psm_fdr: 1
  peptide_fdr: 1 
  protein_fdr: 1

# TODO
db_search:
  ref: "resources/Database/viral.1.protein.faa"
  search_engine: "-xtandem"
  psm_fdr: 1
  peptide_fdr: 1 
  protein_fdr: 1


ms2rescore:
  RescorePipeline: '"tandem"' # any of ['infer', 'pin', 'tandem', 'maxquant', 'msgfplus', 'peptideshaker']
  RescoreFeatures: '[["searchengine", "ms2pip", "rt"]]' #[["searchengine", "ms2pip", "rt"]],
  RunPercolator: 'true' #boolean
  FragModel: '"HCD"' #fragmentation model used for ms2pip http://compomics.github.io/projects/ms2pip_c#specialized-prediction-models

taxids:
  number_of_taxids: 25

sixpack:
  orfminsize: 15
  additional_parameters: ""


SearchGUI: "/home/jpipart/project/SearchGUI-4.2.7/SearchGUI-4.2.7.jar" # replace path
latency-wait: 60