samples: "resources/test_samples.tsv"
contaminants: "resources/Database/0602_Universal_Contaminants.fasta"
genbank_accessions: "resources/Database/Virus_list_complete_genomes.tsv"
result_dir: "results"

host_filtering:
  skip_host_filtering: False
  search_engine: "-xtandem"
  psm_fdr: 1
  peptide_fdr: 1 
  protein_fdr: 1

db_search:
  ref: "resources/Database/refSeqViral.fasta"
  search_engine: "-xtandem"
  psm_fdr: 1
  peptide_fdr: 1 
  protein_fdr: 1


ms2rescore:
  RescorePipeline: '"tandem"' # any of ['infer', 'pin', 'tandem', 'maxquant', 'msgfplus', 'peptideshaker']
  RescoreFeatures: '[["searchengine", "ms2pip", "rt"]]' #[["searchengine", "ms2pip", "rt"]],
  RunPercolator: 'true' #boolean
  FragModel: '"HCD"' #fragmentation model used for ms2pip http://compomics.github.io/projects/ms2pip_c#specialized-prediction-models

mapping:
  number_of_taxids: 5
  max_weight_differences: 2 # how many times should the value be bigger to not consider lower values, ex. 10 is 5 times bigger than 2, so the taxid with weight 2 is not considered for further analysis
  number_of_strains: 10

fetchData:
  max_number_accessions: 200
  sequence_length_diff: 2

sixpack:
  orfminsize: 25 # how many AAs are required for the ORF
  additional_parameters: ""


SearchGUI: "/home/jpipart/project/SearchGUI-4.2.7/SearchGUI-4.2.7.jar" # replace path, conda version yields errors
PeptideShaker: "/home/jpipart/project/PeptideShaker-2.2.22/PeptideShaker-2.2.22.jar" # replace path, conda version yields errors
latency-wait: 60

final_db_search:
  extra: "-Xmx8000m" # specify RAM for java env

pepgm_path: "/home/jpipart/PepGM"

Entrez:
  APIMail: ""
  APIKey: ""