samples: "resources/test_samples.tsv"
result_dir: "results"

host_filtering:
  skip_host_filtering: False
  search_engine: "-xtandem"
  psm_fdr: 1
  peptide_fdr: 1 
  protein_fdr: 1
  host_name: RattusNorvegicus
  host: "resources/Database/GCF_015227675.2_mRatBN7.2_protein.faa"

db_search:
  ref: "resources/Database/refSeqViral.fasta"
  search_engine: "-xtandem"
  psm_fdr: 1
  peptide_fdr: 1 
  protein_fdr: 1